### ISSUE TITLE
Page UI for Typeform Assessment 

### ISSUE THREAD

**Issue by rubyaguilar** [rubyaguilar/GOTV_HearNebraska#12]
This is something to work on when working through the tutorial. Essentially getting an initial UI for the assessment and then much later potentially integrating a pre-made, survey template OR ... making it ... from... scratch...

**Comment by rubyaguilar** [comment]
@MayaMercer should we make a wireframe to present our initial idea for the UI? it probably won't be fully functional and completed by the first release, so we could make one just to give him an idea. 

Another idea is finding various survey templates and asking him which he likes the most and working off that. However, I have a feeling the Typeform ambiance or FYG Life Style Assessment [might](https://findyourgrind.com/assessments/lifestyle-assessment/) be what they are after

**Comment by MayaMercer** [comment]
Yeah that's a good idea---we really need to hash out what's possible in our time frame for UI ideas before we present anything though. 

Here are some open-source options that have that Typeform feel:
- [Conversational form](https://space10-community.github.io/conversational-form/landingpage/) - Makes forms/surveys that look like you're texting someone. Looks pretty easy to use.
- [OhMyForm](https://ohmyform.com/) - Looks like they're trying to be Typeform. 
-[jQuery example](https://codepen.io/Willvlad/pen/GRgmeZO) - Just a simple template with jQuery but you could build off of it.

Let me know what you're thinking.

**Comment by rubyaguilar** [comment]
Thanks for finding these! It definitely seems like they really want a single page UI that scrolls down, so we'll need to figure out how to do voter registration checks, etc. with a single page UI like Typeform, OhMyForm and the jQuery example. I think embeds wouldn't look very clean, so we'll need to talk through that.

**Comment by rubyaguilar** [comment]
Maybe for the first release, we can just present something from https://www.invisionapp.com/. The pros with using these is that they are usually drag and drop editable, so we won't have to go through code when he wants to change something. We just need to make sure we don't design something that we couldn't deliver, lol. We'll need to talk more about it

**Comment by MayaMercer** [comment]
I agree. Sounds good.

**Comment by rubyaguilar** [comment]
@MayaMercer an [intro vid to invision](https://www.youtube.com/watch?v=v10t2azNaFs). it seems complicated/overwhelming at first but once you download invison studio and play around with it it becomes a lot simpler. i sent you an invite to our workspace (https://gotvhearne.invisionapp.com/)

**Comment by rubyaguilar** [comment]
@MayaMercer Oh I really like the freehand: https://www.youtube.com/watch?v=aqdn7vVKygA

I am going to make a couple designs in the workspace before I make them in Invision Studio.

**Comment by rubyaguilar** [comment]
![Uploading IMG_7258.jpg…]()

**Comment by rubyaguilar** [comment]
![IMG_7258](https://user-images.githubusercontent.com/42496681/86316250-ed3e0a80-bbf1-11ea-9db7-56132ddf1e31.jpg)

**Comment by MayaMercer** [comment]
I made a UI focused design [on the right of your initial sketches](https://gotvhearne.invisionapp.com/freehand/GOTV-UI-Freehand-B4ZsS7fUk). Let's keep iterating! Wooh!

**Comment by rubyaguilar** [comment]
Completion is dependent on #5

**Comment by rubyaguilar** [comment]
@MayaMercer Can this be closed? If so feel free to close it and anything else that's done
