### ISSUE TITLE
Which checking if voter registered tool?

### ISSUE THREAD

**Issue by MayaMercer** [rubyaguilar/GOTV_HearNebraska#15]
Options provided by Aaron:
-Rock the Vote
-Vote.org
-Turbovote

**Comment by rubyaguilar** [comment]
This is important for #6. I'm sending emails and trying to get access to one. It seems all these API's do is validate voter registration, so whichever one we can access first works.

**Comment by rubyaguilar** [comment]
@MayaMercer Whichever one we can get access to and working!

**Comment by rubyaguilar** [comment]
@MayaMercer I'm working on this but am stalled. Let me know if you are able to access any.

**Comment by rubyaguilar** [comment]
@MayaMercer 
- TargetSmart is a dead end
- Rock the Vote - i think they only allow by integrating their own embedded code, which sucks
- Vote.org
- Turbovote

**Comment by rubyaguilar** [comment]
@MayaMercer I am going to focus specifically on finding a tool for checking if the voter is registered. Will be putting finding a tool to register on the back burner for now.
