### ISSUE TITLE
Typeform Research

### ISSUE THREAD

**Issue by rubyaguilar** [rubyaguilar/GOTV_HearNebraska#2]
Initial groundwork on Typeform 

Maya: "Voter registratioon first (w/o typeform) then do the profile-quiz after (embed on same page)"

**Comment by MayaMercer** [comment]
https://developer.typeform.com/create/hidden-fields/

**Comment by rubyaguilar** [comment]
Typeform builder does not have custom code integration, so checking voter registration, passing in already entered information (name, address, etc.) can not be carried over. However, can build from scratch to use the Typeform API.
