### ISSUE TITLE
How registering to vote?

### ISSUE THREAD

**Issue by rubyaguilar** [rubyaguilar/GOTV_HearNebraska#25]
Possibly related to #23, unless an API exists for registering to vote (different from checking voter registration, #6 and #15)

**Comment by rubyaguilar** [comment]
https://www.civicnebraska.vote/

**Comment by MayaMercer** [comment]
Went through the process of the sites Aaron recommended. Basically they all have you fill out basic information and then redirect you to [Nebraska's official online voter registration site](https://www.nebraska.gov/apps-sos-voter-registration/). 

- [RockTheVote](https://www.rockthevote.org/programs-and-partner-resources/tech-for-civic-engagement/partner-ovr-tool-faqs/) - No API, but can embed their sign up process. Seems unnecessary if they're just redirecting you to Nebraska's voter registration site. 
- [Vote.org](https://vip.vote.org/) - No API, but can embed their sign up process. Once again, seems unnecessary if they're just redirecting you to Nebraska's voter registration site. 
- [Turbovote](https://turbovote.org/) - Is a bit different than the others as users input their info and Turbovote emails or text them voter information based on their state after that. 

I'll keep exploring for an API, but it seems like the only way you can register to vote in NE is through https://www.nebraska.gov/apps-sos-voter-registration/ which has reCAPTCHA. We should talk through later other ways we can provide value to the user when it comes to voter registration.

**Comment by rubyaguilar** [comment]
@MayaMercer F*Ck

**Comment by rubyaguilar** [comment]
@MayaMercer Yeah, https://www.civicnebraska.vote/ also forwards you to https://www.nebraska.gov/apps-sos-voter-registration/

This is a considerably roadblock since they aren't wanting to switch pages. The only service we're really able to leverage is checking if they are registered to vote.

**Comment by rubyaguilar** [comment]
We'll need to explicitly define the process and pros/cons of each service. I'll do this when I'm designing the system freehand.

**Comment by rubyaguilar** [comment]
DocUSign integration for PDF at https://www.civicnebraska.org/voting-rights/voter-assistance/

**Comment by rubyaguilar** [comment]
@MayaMercer Assigning this to you since it appears you've done more leg work for it. I assigned finding a tool for checking if the voter is registered to myself (APIs exist, just trying to get access)

**Comment by MayaMercer** [comment]
@rubyaguilar 
1. Why do we need DocUSign again?
2. What did we decide on here? Or is this something we're discussing later?

**Comment by rubyaguilar** [comment]
@MayaMercer Yeah was meaning to discuss later. It was an idea at infancy. I was just thinking that maybe instead of having to print the document, fill it out, scan it, and sending it ... an easier process would be to DocUSign and then giving then give them locations where they can print it out and mail it (because I assume this might be a entry barrier for some people) 

I'm just a bit skeptical on what our options are. This could just be another option. It might not be worth it if we can just forward them to nebraska's already-built registering to vote page.

**Comment by MayaMercer** [comment]
I think that whole DocUSign idea could work IF they don't have a valid license, so they can't register through Neb's website. Will talk through later.

**Comment by rubyaguilar** [comment]
@MayaMercer 
Rock The Vote: https://register.rockthevote.com/partner/embed_codes

Accidentally came across this, which seems like you can use to register. Not sure how flexible it is. Is this the redirect to nebraska registration?

**Comment by MayaMercer** [comment]
I got an email about this but not sure where your comment went. 

I signed up for "Rock The Vote: https://register.rockthevote.com/partner/embed_codes" already. It's just a tool you can embed. Forwards you to the Neb website unless you don't have an ID. You can customize how the tool looks, but still just redirects ya.

**Comment by rubyaguilar** [comment]
> I got an email about this but not sure where your comment went.
> 
> I signed up for "Rock The Vote: https://register.rockthevote.com/partner/embed_codes" already. It's just a tool you can embed. Forwards you to the Neb website unless you don't have an ID. You can customize how the tool looks, but still just redirects ya.

Deleted it once I realized it just forwards you to Nebraska page (like you said)
