### ISSUE TITLE
What DB?

### ISSUE THREAD

**Issue by rubyaguilar** [rubyaguilar/GOTV_HearNebraska#4]
Amazon, MongoDB, etc. Costs and performance trade-offs

**Comment by rubyaguilar** [comment]
When you're going through the MERN stack tutorials, you'll come up to when you need to configure a DB, and this would be a good point to look at some of the trade offs in AWS, MongoDB, or potentially any other ones

**Comment by rubyaguilar** [comment]
@MayaMercer https://docs.aws.amazon.com/lambda/latest/dg/with-ddb.html Well DyanmoDB seems promising and setting triggers with Lamdas is so easy. Back stepping on what I said yesterday, I'll probably configure everything with AWS services.

**Comment by MayaMercer** [comment]
@rubyaguilar feeling a little AERNy eh?

**Comment by rubyaguilar** [comment]
@MayaMercer Oi, feelin' hella DERNy! (DynamoDB, Dynotastic, Dyanofantabulous, Dynomaniac, Dinosaur, geography)

**Comment by rubyaguilar** [comment]
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NodeJs.html
