### ISSUE TITLE
Which API for checking if voter registered?

### ISSUE THREAD

**Issue by rubyaguilar** [rubyaguilar/GOTV_HearNebraska#6]
https://docs.targetsmart.com/developers/tsapis/index.html

**Comment by rubyaguilar** [comment]
Need https://duo.com/ mobile app to access API Key

**Comment by MayaMercer** [comment]
Two questions about this service:
1) What's the cost? Need to get a quote and discuss with Aaron if you haven't done that yet.
2) How accurate is the data for Nebraska specifically? I know Nebraska's voter registration check asks for county, and this API doesn't have that for a parameter. Obviously that's not an end-all but raises a red flag for me.

**Comment by rubyaguilar** [comment]
1. When I first met with Aaron, we screen shared access to this API and it gave me an API Key. However, I'm not able to access it anymore? Not sure what's going on. I just requested developer access and emailed client services but assume I won't hear back until Monday. 

2. TargetSmart is used by vote.org, specifically [checking voter registration](https://www.vote.org/am-i-registered-to-vote/). Another layer of assurance is I worked for the Nebraska Democratic Party for all of high school, and we always used Target Smart's NGP VAN product for constituents information from all parties.

**Comment by MayaMercer** [comment]
Ahhh okay great to know! Thanks :)

**Comment by rubyaguilar** [comment]
Registering for a main-in ballot might be more of a challenge than I anticipated. Regardless, the first hurdle will be using an API to validate voter registration. This is just another link I'm pasting here: https://register.rockthevote.com/partner/embed_codes

**Comment by rubyaguilar** [comment]
Dependent on info from #15

**Comment by rubyaguilar** [comment]
TargetSmart is a dead end
Rock the Vote - i think they only allow by integrating their own embedded code, which sucks
Vote.org
Turbovote

**Comment by rubyaguilar** [comment]
@MayaMercer Although this doesn't directly check registration, I think we can deduce that if the query fails, the voter is not registered! https://developers.google.com/civic-information/docs/v2/elections/voterInfoQuery

**Comment by MayaMercer** [comment]
@rubyaguilar maybe... what if it's just basing the query off of the address---regardless if there was someone registered or not? What if multiple people live at an address?

**Comment by MayaMercer** [comment]
If no API can be found - setting up S3 bucket for https://www.votercheck.necvr.ne.gov/voterview would work, right?

**Comment by rubyaguilar** [comment]
> @rubyaguilar maybe... what if it's just basing the query off of the address---regardless if there was someone registered or not? What if multiple people live at an address?

Yeah, I figured that out after the comment. It told me I was registered at an address I don't even live at anymore, lol.

> If no API can be found - setting up S3 bucket for https://www.votercheck.necvr.ne.gov/voterview would work, right?

Yes! I think this S3 bucket implementation might be more integral for the entire system than I wanted. Luckily, once we get it set up once, all of them will be easy. We'll just need to write all the automation code for each URL with https://www.selenium.dev/documentation/en/

**Comment by rubyaguilar** [comment]
<img width="975" alt="Screen Shot 2020-07-10 at 1 45 06 PM" src="https://user-images.githubusercontent.com/42496681/87188033-c186e880-c2b3-11ea-872f-7f80a4d088ea.png">

I thought this was funny. Peep the API endpoint

**Comment by rubyaguilar** [comment]
https://www.eac.gov/sites/default/files/eac_assets/1/6/Federal_Voter_Registration_ENG.pdf

**Comment by rubyaguilar** [comment]
We could (use this)[https://www.vote.org/am-i-registered-to-vote/] or the nebraska page

**Comment by rubyaguilar** [comment]
@MayaMercer Oh yeah!!!!!!!!!!!!!!!!!!!!!!!!!!!

https://alloy.us/verify/

<img width="1250" alt="Screen Shot 2020-07-10 at 2 27 31 PM" src="https://user-images.githubusercontent.com/42496681/87191267-b1720780-c2b9-11ea-8487-380cafe91864.png">

**Comment by MayaMercer** [comment]
OMG YOU ARE INCREDIBLE
