### ISSUE TITLE
Set up practice MERN project 

### ISSUE THREAD

**Issue by rubyaguilar** [rubyaguilar/GOTV_HearNebraska#8]
This will help familiarize with Express, React, and Node.js. The M part (database) will be decided later

**Comment by rubyaguilar** [comment]
Next step will be #6

**Comment by rubyaguilar** [comment]
@MayaMercer Make sure to push your local branch so when we review each others projects we can just do a git checkout

**Comment by rubyaguilar** [comment]
@MayaMercer How do you feel about your understanding of the system architecture? I've done it before a couple times, so if you have any questions just post them. I work with architecture(s) a fair amount, so feel free to ask anything. (I just always forget the nuts and bolts of setting it up)

**Comment by MayaMercer** [comment]
@rubyaguilar Hi Ruby! I feel **okay** about it. Will probably have some questions moving forward.
